name: altitrace

services:
  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://api.altitrace.reachaltitude.xyz
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - INTERNAL_API_URL=http://172.31.20.73:8080
    restart: unless-stopped

volumes:
  redis-data:
    name: altitrace-redis-data
