environment = "production"

[redis]
url = "redis://localhost"

[server]
host = "0.0.0.0"
port = 8080

[api]
rate_limit_requests = 1000
rate_limit_duration = 60
auth_token = ""

[api.cors]
allowed_origins = [
    "https://altitrace.com",
    "https://www.altitrace.com",
    "https://api.altitrace.com"
]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = [
    "accept",
    "accept-language", 
    "content-type",
    "authorization",
    "x-requested-with",
    "x-api-key"
]
allow_credentials = true
max_age = 86400
