environment = "test"

[redis]
url = "redis://localhost"

[server]
host = "127.0.0.1"
port = 8080

[api]
rate_limit_requests = 100
rate_limit_duration = 60
auth_token = ""
base_url = "http://localhost:8080"

[api.cors]
allowed_origins = ["*"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD"]
allowed_headers = ["*"]
allow_credentials = true
max_age = 3600
